PROJECT_NAME: Backend Example
APP_TITLE: Backend Example
APP_DESCRIPTION: Example for backend
DATABASE:
  URL: sqlite:///example.db
  SCHEMA:
REDIS:
  URL: ''
  CLUSTER: false
  KEY_PREFIX: example
SYSTEM:
  RESET_CONFIG_ON_START: false
  WEBUI_URL: ''
  WEBHOOK_URL: ''
  DEFAULT_USER_PERMISSIONS:
    access_grants:
      allow_users: true
    features:
      api_keys: false
      folders: true
      webhooks: false
    settings:
      interface: true
  FILE_MAX_COUNT:
  FILE_MAX_SIZE:
  ALLOWED_FILE_EXTENSIONS: []
  ENABLE_FOLDERS: false
  FOLDER_MAX_FILE_COUNT: ''
  AUTH:
    ENABLE: true
    ADMIN_EMAIL: admin@example.com
    ADMIN_PASSWORD: ''
    ADMIN_NAME: Admin
    JWT_EXPIRES_IN: 1w
    COOKIE_NAME: example-session
  OAUTH:
    ENABLE_OAUTH_SIGNUP: false
  UI:
    ENABLE_SIGNUP: true
    ENABLE_LOGIN_FORM: true
    ENABLE_PASSWORD_CHANGE_FORM: true
    DEFAULT_LOCALE: ''
    DEFAULT_USER_ROLE: pending
    DEFAULT_GROUP_ID: ''
    ENABLE_USER_WEBHOOKS: false
  AUDIT:
    INCLUDED_PATHS: []
    EXCLUDED_PATHS: []
    LOG_LEVEL: NONE
    ENABLE_GET_REQUESTS: false
  STORAGE_PROVIDER: local
SPEC: {}