version: 1
disable_existing_loggers: false
formatters:
  basic:
    datefmt: '%Y-%m-%d %H:%M:%S'
    format: '%(asctime)s.%(msecs)03d - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d:%(funcName)s] - %(message)s'
  colored:
    (): colorlog.ColoredFormatter
    log_colors:
      DEBUG: white
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: bold_red
    datefmt: '%Y-%m-%d %H:%M:%S'
    format: '%(log_color)s%(asctime)s.%(msecs)03d - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d:%(funcName)s] - %(message)s'
  json:
    (): ext://log.CustomJsonFormatter
    format: '%(asctime)s %(levelname)s %(name)s %(module)s %(filename)s %(funcName)s %(lineno)s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
    timestamp: true
    json_indent: 2
    json_ensure_ascii: false
    json_default:
    rename_fields:
      levelname: level
    static_fields:
      app: {{ NAME | default('example') }}
      env: {{ ENV | default('dev') }}
      account: {{ ACCOUNT | default('test') }}
      # version: ext://
  jsonl:
    (): ext://log.CustomJsonFormatter
    format: '%(asctime)s %(levelname)s %(name)s %(module)s %(filename)s %(funcName)s %(lineno)s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
    timestamp: true
    json_indent: null
    json_ensure_ascii: false
    json_default:
    rename_fields:
      levelname: level
    static_fields:
      app: {{ NAME | default('example') }}
      env: {{ ENV | default('dev') }}
      account: {{ ACCOUNT | default('test') }}
  uvicorn-access:
    (): ext://log.CustomJsonFormatter
    format: '%(asctime)s %(levelname)s %(name)s %(module)s %(filename)s %(funcName)s %(lineno)s %(client_addr)s %(request_line)s %(status_code)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
    timestamp: true
    json_indent: null
    json_ensure_ascii: false
    json_default:
    rename_fields:
      levelname: level
    static_fields:
      app: {{ NAME | default('example') }}
      env: {{ ENV | default('dev') }}
      account: {{ ACCOUNT | default('test') }}
  gunicorn-access:
    (): ext://log.CustomJsonFormatter
    format: '%(asctime)s %(levelname)s %(name)s %(module)s %(filename)s %(funcName)s %(lineno)s %(h)s %(l)s %(u)s %(t)s %(r)s %(s)s %(b)s %(f)s %(a)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
    timestamp: true
    json_indent: null
    json_ensure_ascii: false
    json_default:
    rename_fields:
      levelname: level
    static_fields:
      app: {{ NAME | default('example') }}
      env: {{ ENV | default('dev') }}
      account: {{ ACCOUNT | default('test') }}
handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    level: INFO
    formatter: colored
  file:
    class: logging.handlers.RotatingFileHandler
    filename: logs/{{ NAME | default('example') }}.{{ ENV | default('dev') }}.{{ ACCOUNT | default('test') }}.log
    mode: a
    encoding: utf-8
    maxBytes: {{ 1024 * 1024 * 100 }}
    backupCount: 3
    level: DEBUG
    formatter: basic
  jsonl:
    class: logging.handlers.TimedRotatingFileHandler
    filename: logs/{{ NAME | default('example') }}.{{ ENV | default('dev') }}.{{ ACCOUNT | default('test') }}.jsonl
    when: midnight
    interval: 1
    backupCount: 7
    utc: false
    atTime: null
    encoding: utf-8
    level: DEBUG
    formatter: jsonl
  audit:
    class: logging.handlers.TimedRotatingFileHandler
    filename: logs/audit.jsonl
    when: midnight
    interval: 1
    backupCount: 7
    utc: false
    atTime: null
    encoding: utf-8
    level: DEBUG
    formatter: jsonl
  uvicorn-access:
    class: logging.handlers.TimedRotatingFileHandler
    filename: logs/uvicorn.access.jsonl
    when: midnight
    interval: 1
    backupCount: 7
    utc: false
    atTime: null
    encoding: utf-8
    level: DEBUG
    formatter: uvicorn-access
  gunicorn-access:
    class: logging.handlers.TimedRotatingFileHandler
    filename: logs/gunicorn.access.jsonl
    when: midnight
    interval: 1
    backupCount: 7
    utc: false
    atTime: null
    encoding: utf-8
    level: DEBUG
    formatter: gunicorn-access
loggers:
  root:
    level: DEBUG
    handlers:
      - jsonl
      - console
  audit:
    level: INFO
    handlers:
      - audit
  alembic:
    level: INFO
    propagate: false
    handlers:
      - console
  urllib3:
    level: INFO
    propagate: false
    handlers:
      - file
  httpcore:
    level: INFO
    propagate: false
    handlers:
      - file
  httpx:
    level: INFO
    propagate: false
    handlers:
      - file
  hpack.hpack:
    level: INFO
    propagate: false
    handlers:
      - file
  uvicorn:
    level: INFO
    propagate: false
    handlers:
    - jsonl
    - console
  uvicorn.error:
    level: INFO
  uvicorn.access:
    level: INFO
    propagate: false
    handlers:
      - uvicorn-access
  gunicorn:
    level: INFO
    propagate: false
    handlers:
      - jsonl
      - console
  gunicorn.error:
    level: INFO
  gunicorn.access:
    level: INFO
    propagate: false
    handlers:
      - gunicorn-access
  fastapi:
    level: DEBUG
    propagate: false
    handlers:
      - file
  websockets:
    level: INFO
    propagate: false
    handlers:
      - file
  sqlalchemy.engine.Engine:
    level: ERROR
    propagate: false
    handlers:
      - file
    filters: []
  sqlalchemy.pool.impl.QueuePool:
    level: ERROR
    propagate: false
    handlers:
      - file
    filters: []
filters: []